import {defaultBank} from './questions.js';
import {points,durations,validateBank} from './engine.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rounds=['Khởi động','Vượt chướng ngại vật','Tăng tốc','Về đích','Câu hỏi phụ'],keys=['warm','obstacle','speed','finish','tie'];
let bank=structuredClone(defaultBank),state=fresh(),history=[],timer=null,deadline=0,sound=true;
function fresh(){return {round:0,index:0,team:0,teams:['Đội Trí Tuệ','Đội Bản Lĩnh','Đội Khát Vọng','Đội Tiên Phong'].map(name=>({name,score:0})),phase:'ready',left:3,buzzer:null,arrivals:[],judged:[],clues:[],opened:[],clue:0,guess:false,blocked:[],value:20,star:false,stars:[],steal:false,tieEligible:[0,1,2,3],tieWinner:null,log:'Sẵn sàng cho hành trình chinh phục đỉnh cao.'};}
try{const saved=JSON.parse(localStorage.getItem('olympia-v1'));if(saved){validateBank(saved.bank);validateState(saved.state);bank=saved.bank;state={...fresh(),...saved.state,phase:'ready',buzzer:null,arrivals:[],judged:[]};}}catch{localStorage.removeItem('olympia-v1');}
function save(){try{localStorage.setItem('olympia-v1',JSON.stringify({bank,state}));$('#saved').textContent='✓ Đã lưu trên thiết bị';}catch{$('#saved').textContent='Không thể lưu — hãy xuất bản sao';}}
function checkpoint(){history.push(structuredClone(state));if(history.length>60)history.shift();}
function log(s){state.log=s;save();}
function q(){return state.round===0?bank.warm[state.index]:state.round===1?(state.clue===4?bank.obstacle.center:bank.obstacle.clues[state.clue]):state.round===2?bank.speed[state.index]:state.round===3?bank.finish[state.index]:bank.tie[state.index];}
function duration(){return state.round===0?3:state.round===1?15:state.round===2?durations.speed[state.index]:state.round===3?durations.finish[state.value]:15;}
function clearClock(){clearInterval(timer);timer=null;}
function resetQuestion(){clearClock();state.phase='ready';state.left=duration();state.buzzer=null;state.arrivals=[];state.judged=[];state.steal=false;state.star=false;state.guess=false;$('#answer').hidden=true;}
function beep(){if(!sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=660;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.3);o.start();o.stop(c.currentTime+.3);o.onended=()=>c.close();}catch{}}
function runClock(seconds){clearClock();state.left=seconds;deadline=performance.now()+seconds*1000;timer=setInterval(()=>{state.left=Math.max(0,Math.ceil((deadline-performance.now())/1000));$('#seconds').textContent=String(state.left).padStart(2,'0');if(state.left===0){clearClock();expire();}},50);render();}
function start(){if(state.phase!=='ready')return;checkpoint();if(state.round===1&&!state.clues.includes(state.clue))state.clues.push(state.clue);state.phase='running';if(state.round===3&&state.star&&!state.stars.includes(state.team))state.stars.push(state.team);state.started=Date.now();log('Đồng hồ bắt đầu.');runClock(duration());}
function expire(){beep();if(state.round===0&&state.index>=24){if(state.buzzer!==null){score(state.buzzer,-5);state.judged.push(state.buzzer);log(`${name(state.buzzer)} hết giờ trả lời: −5 điểm.`);}else log('Không có chuông trong 3 giây. Bỏ qua câu hỏi.');state.phase='done';}else{state.phase='expired';log('Hết thời gian. MC chấm đáp án đã nhận.');}render();save();}
function name(i){return state.teams[i].name;}function score(i,n){state.teams[i].score+=n;}
function buzz(i){if($('#dialog').open)return;if(state.round===0&&state.index<24)return;if(state.round===3&&!state.steal)return;if(state.round===1&&!state.guess)return;if(state.round===4&&(!state.tieEligible.includes(i)||state.blocked.includes(i)||state.tieWinner!==null))return;if(state.phase==='ready'&&state.round===4){checkpoint();state.blocked.push(i);log(`${name(i)} bấm trước hiệu lệnh, mất quyền trả lời câu này.`);render();return;}if(state.phase!=='running'||state.buzzer!==null)return;if(timer&&performance.now()>=deadline){clearClock();expire();return;}if(state.round===2){if(state.arrivals.some(a=>a.i===i))return;state.arrivals.push({i,time:Date.now()-state.started});log(`${name(i)} đã nộp đáp án (${((Date.now()-state.started)/1000).toFixed(2)}s).`);beep();render();return;}if(state.round===3&&i===state.team)return;checkpoint();state.buzzer=i;beep();log(`${name(i)} giành quyền trả lời. MC chỉ ghi nhận đáp án đầu tiên.`);if(state.round===0){runClock(3);}else{clearClock();state.phase='answering';render();}}
function judge(i,correct){if(state.judged.includes(i)||state.phase==='ready'||state.phase==='done')return;checkpoint();let r=keys[state.round];if(r==='tie'){if(correct){state.tieWinner=i;state.phase='done';log(`🏆 ${name(i)} chiến thắng câu hỏi phụ!`);}else{state.blocked.push(i);state.buzzer=null;state.phase='running';runClock(Math.max(1,state.left));log(`${name(i)} trả lời sai. Các đội còn lại tiếp tục.`);}render();save();return;}
if(r==='speed'){return;}const delta=points(r,{correct,common:state.index>=24,value:state.value,star:state.star,steal:state.steal,clue:Math.max(0,state.clues.length-1),guess:state.guess});score(i,delta);state.judged.push(i);if(r==='finish'&&state.steal&&correct)score(state.team,-state.value);
if(r==='obstacle'&&!state.guess){if(correct&&!state.opened.includes(state.clue))state.opened.push(state.clue);}else if(r==='finish'&&!state.steal&&!correct){clearClock();state.phase='steal-ready';}else{clearClock();state.phase='done';}
if(r==='obstacle'&&state.guess&&!correct){state.blocked.push(i);state.guess=false;state.phase='ready';state.buzzer=null;state.judged=[];}
log(`${name(i)}: ${correct?'chính xác':'chưa chính xác'} (${delta>=0?'+':''}${delta} điểm).`);render();save();}
function next(){const max=[36,5,4,12,3][state.round];if(state.round===4&&state.tieWinner!==null){showWinner(state.tieWinner);return;}if(state.index>=max-1){if(state.round===4){draw();return;}if(state.round===1){changeRound(2);return;}changeRound(state.round+1);return;}checkpoint();state.index++;if(state.round===0&&state.index<24)state.team=Math.floor(state.index/6);if(state.round===3)state.team=Math.floor(state.index/3);if(state.round===1)state.clue=state.index;if(state.round===4)state.blocked=[];resetQuestion();log('Đã chuyển sang câu tiếp theo.');render();save();}
function changeRound(i){checkpoint();state.round=i;state.index=0;state.team=0;state.clue=0;state.blocked=[];state.tieWinner=null;if(i===4){const max=Math.max(...state.teams.map(t=>t.score));state.tieEligible=state.teams.flatMap((t,i)=>t.score===max?[i]:[]);if(state.tieEligible.length===1){showWinner(state.tieEligible[0]);}}
resetQuestion();log(`Chuyển sang vòng ${rounds[i]}.`);render();save();}
function showWinner(i){modal('Vòng nguyệt quế',`<div style="text-align:center;padding:24px"><div style="font-size:60px">🏆</div><h2>${esc(name(i))}</h2><p>${state.teams[i].score} điểm · Chúc mừng nhà vô địch!</p></div>`);}
function draw(){if(state.tieWinner!==null)return;checkpoint();const ids=state.tieEligible;const n=crypto.getRandomValues(new Uint32Array(1))[0];state.tieWinner=ids[n%ids.length];state.phase='done';log(`Sau 3 câu phụ, bốc thăm chọn ${name(state.tieWinner)} thắng cuộc.`);save();render();showWinner(state.tieWinner);}
function render(){const r=state.round,question=q();$('#rounds').innerHTML=rounds.map((n,i)=>`<button data-round="${i}" class="${r===i?'active':''}"><span>0${i+1}</span>${n}</button>`).join('');$('#stage-label').textContent=`0${r+1} / ${rounds[r].toUpperCase()}`;$('#qnumber').textContent=r===0?(state.index<24?`PHẦN THI RIÊNG • CÂU ${state.index%6+1} / 6`:`PHẦN THI CHUNG • CÂU ${state.index-23} / 12`):`CÂU ${state.index+1} / ${[36,5,4,12,3][r]}`;$('#category').textContent=r===0?'+10 ĐIỂM':r===1?'15 GIÂY':r===2?'40 · 30 · 20 · 10':r===3?`${state.value} ĐIỂM${state.star?' × 2':''}`:'PHÂN ĐỊNH THẮNG THUA';$('#question').textContent=state.guess?'Đâu là chướng ngại vật cần tìm?':question.text;$('#answer').textContent=`Đáp án: ${state.guess?bank.obstacle.answer:question.answer}`;$('#media').innerHTML=media(question);$('#seconds').textContent=String(state.left).padStart(2,'0');$('#clock').className='clock '+(timer?'running':state.left===0?'expired':'');$('#status').textContent=state.buzzer!==null?`${name(state.buzzer)} giành quyền trả lời`:({ready:'Sẵn sàng bắt đầu',running:'Thời gian đang đếm ngược',expired:'Đã hết thời gian',done:'Đã hoàn thành câu hỏi',answering:'Đang trả lời', 'steal-ready':'Mở quyền trả lời cho đội khác'})[state.phase];$('#hint').textContent=r===0&&state.index<24?`${name(state.team)} đang thi • Tính giờ sau khi MC đọc xong.`:r===2?'Nhấn phím 1–4 khi nhận đáp án của mỗi đội. MC xác nhận đúng/sai.':r===4?'Chỉ các đội bằng điểm cao nhất tham gia. Bấm sớm sẽ mất quyền.':'MC đọc xong câu hỏi rồi bắt đầu tính giờ. Phím 1–4 để bấm chuông.';$('#progress').textContent=`${rounds[r].toUpperCase()} / ${String(state.index+1).padStart(2,'0')}`;
$('#teams').innerHTML=state.teams.map((t,i)=>`<button class="team ${(state.buzzer??state.team)===i?'selected':''}" data-team="${i}" aria-label="${esc(t.name)}: ${t.score} điểm"><span class="avatar">0${i+1}</span><span class="team-name"><b>${esc(t.name)}</b><small>${state.blocked.includes(i)?'Mất quyền trả lời':state.arrivals.some(a=>a.i===i)?'✓ Đã nộp đáp án':`PHÍM ${i+1} · ĐỘI CHƠI`}</small></span><span class="score">${t.score}</span></button>`).join('');$('#log').textContent=state.log;$('#start').disabled=state.phase!=='ready';$('#start').textContent='▶ Bắt đầu tính giờ';$('#undo').disabled=!history.length;$('#next').disabled=!!timer;$('#next').textContent=r===4&&state.index===2?'Bốc thăm / Kết quả →':'Câu tiếp theo →';$('#reveal').disabled=!!timer;
$('#special').innerHTML=r===1?`<div class="clues">${[...bank.obstacle.clues,bank.obstacle.center].map((c,i)=>`<button data-clue="${i}" class="${state.opened.includes(i)?'open':''}">${i===4?'Ô trung tâm':`Hàng ${i+1}`} ${state.opened.includes(i)?'✓':''}</button>`).join('')}</div>${bank.obstacle.image?`<div class="tiles"><img src="${esc(safeURL(bank.obstacle.image))}" alt="Hình gợi ý chướng ngại vật">${[0,1,2,3].map(i=>`<span class="${state.opened.includes(i)?'uncovered':''}">${i+1}</span>`).join('')}<span class="center-tile ${state.opened.includes(4)?'uncovered':''}">★</span></div>`:''}<p>Chướng ngại vật: ${bank.obstacle.answer.replace(/\s/g,'').length} ký tự · Đúng lúc này: ${[60,50,40,30,20][Math.max(0,state.clues.length-1)]} điểm</p>`:'';
$('#options').innerHTML=r===0?`<select id="warm-mode" aria-label="Chọn phần khởi động"><option value="0" ${state.index<24?'selected':''}>Khởi động riêng</option><option value="24" ${state.index>=24?'selected':''}>Khởi động chung</option></select>${state.index<24?teamSelect():''}`:r===3?`${teamSelect()}<select id="value" aria-label="Điểm câu hỏi"><option ${state.value===20?'selected':''}>20</option><option ${state.value===30?'selected':''}>30</option></select><button id="star" class="${state.star?'star-on':''}" ${state.stars.includes(state.team)||state.phase!=='ready'?'disabled':''}>★ Ngôi sao hy vọng</button>`:r===1?`<button id="guess" ${state.guess?'disabled':''}>✦ Trả lời chướng ngại vật</button>`:r===4?`<span>Đội tham gia: ${state.tieEligible.map(i=>esc(name(i))).join(', ')}</span>`:`<span style="color:#8b9bb5;font-size:11px">${esc(question.type||'Tăng tốc')}</span>`;
let judging='';if(r===2){judging=state.arrivals.map(a=>`<label><input type="checkbox" data-correct="${a.i}" checked ${state.phase==='done'?'disabled':''}> ${esc(name(a.i))} · ${(a.time/1000).toFixed(2)}s</label>`).join('')+`<button id="score-speed" ${!['expired'].includes(state.phase)?'disabled':''}>Chấm đáp án đã chọn đúng</button>`;}else if(r===1&&!state.guess){judging=state.teams.map((t,i)=>`<button data-judge="${i}:1" class="good" ${state.phase==='ready'||state.blocked.includes(i)||state.judged.includes(i)?'disabled':''}>✓ ${esc(t.name)} +10</button>`).join('');}else{const i=state.buzzer??state.team;const eligible=r===0&&state.index<24||r===3&&!state.steal||state.buzzer!==null;const disabled=!eligible||['ready','done','steal-ready'].includes(state.phase)||state.judged.includes(i);judging=`<button class="good" data-judge="${i}:1" ${disabled?'disabled':''}>✓ Chính xác</button><button class="bad" data-judge="${i}:0" ${disabled?'disabled':''}>✕ Chưa chính xác</button>`;if(state.phase==='steal-ready')judging+='<button id="steal">Mở chuông giành điểm (MC kết thúc thủ công)</button>';}
$('#judging').innerHTML=judging;bindDynamic();}
function safeURL(s){return /^(https?:\/\/|assets\/)/.test(s)?s:'';}
function media(q){if(!q.media)return '';const src=esc(safeURL(q.media));return q.mediaType==='audio'?`<audio controls src="${src}"></audio>`:q.mediaType==='video'?`<video controls src="${src}"></video>`:`<img src="${src}" alt="Hình ảnh gợi ý câu hỏi">`;}
function teamSelect(){return `<select id="team-select" aria-label="Đội đang thi">${state.teams.map((t,i)=>`<option value="${i}" ${i===state.team?'selected':''}>${esc(t.name)}</option>`).join('')}</select>`;}
function bindDynamic(){document.querySelectorAll('[data-round]').forEach(el=>el.onclick=()=>changeRound(+el.dataset.round));document.querySelectorAll('[data-team]').forEach(el=>el.onclick=()=>buzz(+el.dataset.team));document.querySelectorAll('[data-judge]').forEach(el=>el.onclick=()=>{let [i,c]=el.dataset.judge.split(':').map(Number);judge(i,!!c);});document.querySelectorAll('[data-clue]').forEach(el=>el.onclick=()=>{if(+el.dataset.clue===4&&state.clues.filter(i=>i<4).length<4){log('Cần hoàn thành 4 hàng ngang trước ô trung tâm.');render();return;}checkpoint();state.clue=+el.dataset.clue;state.index=state.clue;resetQuestion();render();save();});$('#warm-mode')?.addEventListener('change',e=>{checkpoint();state.index=+e.target.value;state.team=0;resetQuestion();render();save();});$('#team-select')?.addEventListener('change',e=>{checkpoint();state.team=+e.target.value;state.index=state.team*(state.round===0?6:3);resetQuestion();render();save();});$('#value')?.addEventListener('change',e=>{if(state.phase!=='ready')return;state.value=+e.target.value;state.left=duration();render();save();});$('#star')?.addEventListener('click',()=>{state.star=!state.star;render();});$('#guess')?.addEventListener('click',()=>{checkpoint();clearClock();state.guess=true;state.phase='running';state.buzzer=null;state.judged=[];log('Mở chuông trả lời chướng ngại vật.');runClock(15);});$('#steal')?.addEventListener('click',()=>{state.steal=true;state.buzzer=null;state.judged=[];state.phase='running';log('Đội khác bấm chuông giành điểm. Chỉ nhận đáp án đầu tiên.');render();});$('#score-speed')?.addEventListener('click',()=>{checkpoint();const checked=[...document.querySelectorAll('[data-correct]:checked')].map(e=>+e.dataset.correct);let rank=0;state.arrivals.slice().sort((a,b)=>a.time-b.time).forEach(a=>{if(checked.includes(a.i))score(a.i,points('speed',{rank:rank++}));});state.phase='done';log(`Đã chấm Tăng tốc: ${rank} đáp án đúng theo thứ tự nộp.`);render();save();});}
function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
$('#close').onclick=()=>$('#dialog').close();$('#start').onclick=start;$('#next').onclick=next;$('#reveal').onclick=()=>{$('#answer').hidden=!$('#answer').hidden;};$('#undo').onclick=()=>{if(!history.length)return;clearClock();state=history.pop();state.phase='ready';state.left=duration();state.buzzer=null;$('#answer').hidden=true;render();save();};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'♫ Âm thanh':'♫ Tắt âm';};$('#present').onclick=()=>{document.body.classList.toggle('presentation');$('#answer').hidden=true;$('#present').textContent=document.body.classList.contains('presentation')?'⛶ Thoát trình chiếu':'⛶ Trình chiếu';};document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#dialog').open)return;if(['1','2','3','4'].includes(e.key)){e.preventDefault();buzz(+e.key-1);}if(e.code==='Space'){e.preventDefault();start();}});
$('#rules').onclick=()=>modal('Luật cuộc thi',`<p class="notice">Áp dụng bộ luật bạn cung cấp. MC quyết định đúng/sai; thời gian bắt đầu sau hiệu lệnh hoặc sau khi đọc xong câu hỏi.</p><h3>01 · Khởi động</h3><p>Riêng: mỗi đội 6 câu, 3 giây/câu; đúng +10, sai không trừ. Chung: 12 câu; không có chuông sau 3 giây thì bỏ qua. Đội giành chuông có 3 giây trả lời, đúng +10, sai hoặc hết giờ −5. Hỗ trợ câu hỏi điền đáp án, lựa chọn, hình ảnh/âm thanh.</p><h3>02 · Vượt chướng ngại vật</h3><p>4 hàng ngang, mỗi câu 15 giây, đúng +10. Chướng ngại vật đúng trong lần lượt 1/2/3/4 hàng ngang: 60/50/40/30 điểm. Ô trung tâm: đúng +10 và mở hình, sai giữ kín. Sau gợi ý cuối, có 15 giây đoán chướng ngại vật, đúng +20.</p><h3>03 · Tăng tốc</h3><p>4 câu: nhìn nhanh, sắp xếp, suy luận, đoạn băng. Thời gian 20–20–30–30 giây. Các đáp án đúng theo thứ tự nộp nhận 40–30–20–10 điểm. MC nhấn phím đội khi nhận bài, bỏ chọn đáp án sai rồi chấm sau khi hết giờ.</p><h3>04 · Về đích</h3><p>Câu 20 điểm: 15 giây; câu 30 điểm: 20 giây. Đội giành quyền trả lời đúng nhận điểm từ đội đang thi; sai bị trừ nửa giá trị câu hỏi. Ngôi sao hy vọng: đúng gấp đôi, sai trừ giá trị câu dù đội khác có giành quyền hay không. Chỉ ghi nhận đáp án đầu tiên của đội giành chuông.</p><h3>05 · Câu hỏi phụ</h3><p>3 câu, mỗi câu 15 giây. Đội bấm trước hiệu lệnh mất quyền câu đó. Nếu không có đội thắng sau 3 câu thì bốc thăm.</p><h3>Quy ước vận hành</h3><p>Mặc định 4 đội, 3 câu Về đích/đội, mỗi đội dùng sao một lần. Đoán sai chướng ngại vật mất quyền vòng này. Đây là quy ước bổ sung cho phần chưa nêu chi tiết. MC điều khiển chuông trên cùng một máy; website không đồng bộ chuông giữa nhiều thiết bị. Chỉ đội bằng điểm cao nhất tham gia câu phụ.</p>`);
$('#sources').onclick=()=>modal('Hướng dẫn & nguồn tham khảo',`<h3>Chạy một trận đấu</h3><p>1. Vào Thiết lập để đặt tên đội và chuẩn bị câu hỏi.<br>2. Chọn vòng, đội thi. Đọc câu hỏi rồi bấm Bắt đầu (hoặc Space).<br>3. Các phím 1–4 là chuông; MC chấm đúng/sai trên bàn điều khiển.<br>4. Trình chiếu ẩn bàn MC và đáp án. Hoàn tác phục hồi thao tác gần nhất.</p><p>Trận lưu trong trình duyệt hiện tại. Xuất bản sao trước khi chuyển máy. MC nên giữ bản đáp án riêng khi trình chiếu; chế độ trình chiếu chỉ ẩn điều khiển, không phải hệ thống bảo mật đáp án.</p><h3>Nhận diện & luật</h3><p>Lấy cảm hứng từ sân khấu xanh/tím, ánh cyan, logo vàng và vòng nguyệt quế của Đường lên đỉnh Olympia. Đây là công cụ cộng đồng, không phải website chính thức của VTV.</p><ul><li><a href="https://vtv.vn/big-story/truc-tiep-chung-ket-duong-len-dinh-olympia-nam-thu-25-8h30-vtv3-100251025210950692.htm" target="_blank" rel="noopener">VTV: Chung kết Olympia năm 25 — cấu trúc các vòng</a></li><li><a href="https://vtv.vn/truyen-hinh/luat-choi-moi-cua-duong-len-dinh-olympia-co-gi-dac-biet-20210926004846313.htm" target="_blank" rel="noopener">VTV: Luật thay đổi theo mùa</a></li><li><a href="https://duong-len-dinh-olympia.fandom.com/vi/wiki/Olympia_25" target="_blank" rel="noopener">Nguồn ảnh logo/titlecard: Olympia Wiki; nhận diện chương trình thuộc VTV</a></li></ul><p>Bộ câu hỏi đi kèm là nội dung mẫu để thử hệ thống, không phải đề chính thức. Câu đoạn băng cần MC thêm video. Tính điểm ưu tiên bộ luật được yêu cầu.</p>`);
function download(data,file){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#settings').onclick=()=>{modal('Thiết lập cuộc thi',`<h3>Bốn đội chơi</h3>${state.teams.map((t,i)=>`<label>Đội ${i+1}<input id="name-${i}" maxlength="40" value="${esc(t.name)}"><input id="score-${i}" type="number" value="${t.score}" aria-label="Điểm đội ${i+1}" style="width:85px"></label>`).join('')}<button id="save-teams" class="primary">Lưu đội & điểm</button><h3>Bộ câu hỏi</h3><p>Chỉnh JSON bên dưới hoặc nhập tệp. warm: 36 câu (24 riêng + 12 chung), speed: 4, finish: 12, tie: 3. Mỗi câu có text, answer; thêm media và mediaType (image/audio/video) để dùng đa phương tiện. obstacle chứa 4 clues, center, answer và image tùy chọn.</p><textarea id="bank-editor" aria-label="Bộ câu hỏi JSON">${esc(JSON.stringify(bank,null,2))}</textarea><p id="editor-message" role="status"></p><input type="file" id="import-bank" accept=".json,application/json" aria-label="Nhập bộ câu hỏi"><button id="save-bank" class="primary">Áp dụng bộ câu hỏi</button><button id="export-bank">Tải bộ câu hỏi</button><h3>Dữ liệu trận đấu</h3><button id="export-match">Xuất bản sao trận</button><label>Khôi phục bản sao <input type="file" id="import-match" accept=".json,application/json"></label><button id="reset" class="bad">Tạo trận mới (giữ bộ câu hỏi)</button><p id="settings-message" role="status"></p>`);$('#save-teams').onclick=()=>{const teams=state.teams.map((t,i)=>({name:$(`#name-${i}`).value.trim()||`Đội ${i+1}`,score:Number($(`#score-${i}`).value)}));if(teams.some(t=>!Number.isFinite(t.score)||Math.abs(t.score)>100000)){$('#settings-message').textContent='Điểm không hợp lệ.';return;}checkpoint();state.teams=teams;render();save();$('#settings-message').textContent='Đã lưu tên và điểm các đội.';};$('#save-bank').onclick=()=>{try{const b=validateBank(JSON.parse($('#bank-editor').value));checkpoint();bank=b;resetQuestion();render();save();$('#editor-message').textContent='✓ Đã áp dụng bộ câu hỏi.';}catch(e){$('#editor-message').textContent=e.message;}};$('#import-bank').onchange=async e=>{try{$('#bank-editor').value=JSON.stringify(validateBank(JSON.parse(await e.target.files[0].text())),null,2);$('#editor-message').textContent='Đã đọc tệp. Bấm Áp dụng để lưu.';}catch(err){$('#editor-message').textContent=err.message;}};$('#export-bank').onclick=()=>download(bank,'olympia-questions.json');$('#export-match').onclick=()=>download({bank,state},'olympia-match.json');$('#import-match').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());validateBank(data.bank);validateState(data.state);checkpoint();clearClock();bank=data.bank;state={...fresh(),...data.state};resetQuestion();render();save();$('#settings-message').textContent='Đã khôi phục. Câu hiện tại bắt đầu lại đồng hồ để MC tiếp tục.';}catch(err){$('#settings-message').textContent=err.message;}};$('#reset').onclick=()=>{if(!confirm('Tạo trận mới và xóa điểm hiện tại? Bạn có thể xuất bản sao trước.'))return;checkpoint();clearClock();state=fresh();render();save();$('#dialog').close();};};
function validateState(s){if(!s||!Array.isArray(s.teams)||s.teams.length!==4||s.teams.some(t=>typeof t.name!=='string'||!Number.isFinite(t.score))||!Number.isInteger(s.round)||s.round<0||s.round>4||!Number.isInteger(s.index)||s.index<0||s.index>=[36,5,4,12,3][s.round]||!Number.isInteger(s.team)||s.team<0||s.team>3)throw Error('Bản sao trận không hợp lệ.');for(const key of ['clues','opened','blocked','stars','tieEligible'])if(!Array.isArray(s[key])||s[key].some(i=>!Number.isInteger(i)||i<0||i>(['clues','opened'].includes(key)?4:3)))throw Error('Bản sao chứa danh sách đội/ô không hợp lệ.');if(![20,30].includes(s.value)||!Number.isInteger(s.clue)||s.clue<0||s.clue>4)throw Error('Bản sao có giá trị không hợp lệ.');}
state.left=duration();render();save();
