import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM} from 'jsdom';import {defaultBank} from '../questions.js';import {points,durations,validateBank} from '../engine.js';
function setup(){const dom=new JSDOM(readFileSync(new URL('../index.html',import.meta.url),'utf8'),{url:'https://example.com',runScripts:'outside-only'});const w=dom.window;Object.assign(w,{defaultBank,points,durations,validateBank,structuredClone});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/^import .*;$/mg,'')+'\nwindow.api={get state(){return state},start,buzz,judge,next,changeRound,expire,render,clearClock};');return {w,a:w.api,close:()=>w.close()};}
test('Initial screen renders four teams and hides answer',()=>{const {w,close}=setup();assert.equal(w.document.querySelectorAll('.team').length,4);assert.match(w.document.querySelector('#question').textContent,/Thủ đô/);assert.equal(w.document.querySelector('#answer').hidden,true);close();});
test('Warm-up scores once; undo restores score',()=>{const {w,a,close}=setup();a.start();a.judge(0,true);a.judge(0,true);assert.equal(a.state.teams[0].score,10);w.document.querySelector('#undo').click();assert.equal(a.state.teams[0].score,0);close();});
test('Common buzz locks first team; timeout deducts five',()=>{const {a,close}=setup();a.state.index=24;a.start();a.buzz(2);a.buzz(1);assert.equal(a.state.buzzer,2);a.expire();assert.equal(a.state.teams[2].score,-5);a.clearClock();close();});
test('Hope star wrong plus steal transfers points',()=>{const {w,a,close}=setup();a.changeRound(3);a.state.value=30;a.state.star=true;a.start();a.judge(0,false);assert.equal(a.state.teams[0].score,-30);assert.ok(a.state.stars.includes(0));w.document.querySelector('#steal').click();a.buzz(1);a.judge(1,true);assert.equal(a.state.teams[0].score,-60);assert.equal(a.state.teams[1].score,30);close();});
test('Acceleration excludes wrong response from ranking',()=>{const {w,a,close}=setup();a.changeRound(2);a.start();a.buzz(0);a.buzz(0);a.buzz(1);a.buzz(2);assert.equal(a.state.arrivals.length,3);a.clearClock();a.expire();w.document.querySelector('[data-correct="0"]').checked=false;w.document.querySelector('#score-speed').click();assert.deepEqual(Array.from(a.state.teams,t=>t.score),[0,40,30,0]);assert.equal(w.document.querySelector('#score-speed').disabled,true);close();});
test('Early tiebreak buzz disqualifies team for question',()=>{const {a,close}=setup();a.changeRound(4);a.buzz(0);a.start();a.buzz(0);assert.equal(a.state.buzzer,null);a.buzz(1);a.judge(1,true);assert.equal(a.state.tieWinner,1);close();});
test('Obstacle awards clues and first-clue guess',()=>{const {w,a,close}=setup();a.changeRound(1);a.start();a.judge(0,true);a.judge(0,true);assert.equal(a.state.teams[0].score,10);w.document.querySelector('#guess').click();a.buzz(2);a.judge(2,true);assert.equal(a.state.teams[2].score,60);close();});
