import {hashPassword} from '../multiplayer/access.js';
import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {WebSocket} from 'ws';
import {createRoom,act,snapshot,authenticate,expire} from '../multiplayer/game.js';import {createGameServer} from '../server.js';
const question=(type='text',extra={})=>({type:'question',round:'Khởi động',duration:15,question:{text:'Một cộng một?',solution:'2',type,choices:['1','2','3']},...extra});
test('Only host controls score and question; submitting an answer alone does not score',()=>{const r=createRoom();assert.equal(authenticate(r,'fake'),null);act(r,'host',question());act(r,'host',{type:'start'},100);assert.throws(()=>act(r,'p0',{type:'score',player:0,score:999,questionId:r.questionId},101));assert.throws(()=>act(r,'display',{type:'question'}));act(r,'p0',{type:'answer',questionId:r.questionId,text:'2'},102);assert.equal(r.teams[0].score,0);act(r,'host',{type:'score',player:0,score:35});assert.equal(r.teams[0].score,35);});
test('Answers and solution remain private until MC publishes',()=>{const r=createRoom();act(r,'host',question());act(r,'host',{type:'start'},100);act(r,'p0',{type:'answer',questionId:r.questionId,text:'2'},101);assert.equal(snapshot(r,'p1').answers[0].text,null);assert.equal(snapshot(r,'display').question.solution,undefined);assert.equal(snapshot(r,'p0').answers[0].text,'2');assert.equal(snapshot(r,'host').question.solution,'2');assert.throws(()=>act(r,'host',{type:'revealAnswers',show:true}));act(r,'host',{type:'close'});act(r,'host',{type:'revealAnswers',show:true});assert.equal(snapshot(r,'display').answers[0].text,'2');});
test('Deadline, duplicate answer, stale question and invalid choice are rejected',()=>{const r=createRoom();act(r,'host',question('choice'));act(r,'host',{type:'start'},100);const id=r.questionId;assert.throws(()=>act(r,'p0',{type:'answer',questionId:id,text:'Other'},101));act(r,'p0',{type:'answer',questionId:id,text:'2'},102);assert.throws(()=>act(r,'p0',{type:'answer',questionId:id,text:'1'},103));assert.throws(()=>act(r,'p1',{type:'answer',questionId:id,text:'2'},15100));assert.ok(expire(r,15100));act(r,'host',question());act(r,'host',{type:'start'},20000);assert.throws(()=>act(r,'p1',{type:'answer',questionId:id,text:'2'},20001));});
test('Buzzer assigns one first winner even with equal receive timestamps',()=>{const r=createRoom();act(r,'host',question('buzz'));act(r,'host',{type:'start'},100);for(const role of ['p2','p0','p1'])act(r,role,{type:'buzz',questionId:r.questionId},101);assert.deepEqual(r.buzzes.map(b=>[b.player,b.rank]),[[2,1],[0,2],[1,3]]);assert.throws(()=>act(r,'p2',{type:'buzz',questionId:r.questionId},102));assert.throws(()=>act(r,'p0',{type:'answer',questionId:r.questionId,text:'2'},103));act(r,'p2',{type:'answer',questionId:r.questionId,text:'2'},104);assert.equal(r.answers[2].text,'2');});
test('Obstacle stays hidden until selected; MC opens chosen tile without changing score',()=>{const r=createRoom();act(r,'host',{type:'round',round:'Vượt chướng ngại vật'});assert.equal(snapshot(r,'display').question,null);act(r,'host',question('text',{round:'Vượt chướng ngại vật',clue:2}));act(r,'host',{type:'tile',open:true});assert.deepEqual(r.opened,[2]);assert.equal(r.teams[0].score,0);act(r,'host',{type:'waiting'});assert.equal(r.question,null);assert.deepEqual(r.opened,[2]);assert.throws(()=>act(r,'host',question('text',{round:'Vượt chướng ngại vật',clue:2})));});
function client(url){const ws=new WebSocket(url);let messages=[];ws.on('message',raw=>messages.push(JSON.parse(raw)));return {ws,send:m=>ws.send(JSON.stringify(m)),wait:async predicate=>{const end=Date.now()+2500;while(Date.now()<end){const found=messages.find(predicate);if(found)return found;await new Promise(r=>setTimeout(r,10));}throw Error('Message timeout');},clear:()=>{messages=[];}};}
test('Five independent WebSockets synchronize, arbitrate simultaneous buzzes, and reconnect',async()=>{const {server,wss}=createGameServer({accessHash:hashPassword('test-only-password')});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;const data=await (await fetch(base+'/api/rooms',{method:'POST',headers:{'X-Olympia-Password':'test-only-password'}})).json();const clients=[];try{
 for(const role of ['host','display','p0','p1','p2']){const c=client(base.replace('http','ws'));clients.push(c);await once(c.ws,'open');c.send({type:'join',room:data.id,token:data.tokens[role],password:'test-only-password'});await c.wait(m=>m.type==='state');}
 const [host,display,p0,p1,p2]=clients;host.send(question('buzz'));await Promise.all(clients.map(c=>c.wait(m=>m.type==='state'&&m.state.question?.type==='buzz')));host.send({type:'start'});await Promise.all(clients.map(c=>c.wait(m=>m.type==='state'&&m.state.phase==='open')));
 for(const c of [p0,p1,p2])c.send({type:'buzz',questionId:1});const states=await Promise.all(clients.map(c=>c.wait(m=>m.type==='state'&&m.state.buzzes.length===3)));for(const m of states)assert.deepEqual(m.state.buzzes,states[0].state.buzzes);assert.deepEqual(states[0].state.buzzes.map(b=>b.rank),[1,2,3]);
 p0.send({type:'score',player:0,score:999,questionId:1});await p0.wait(m=>m.type==='error');host.send({type:'score',player:1,score:75});await Promise.all(clients.map(c=>c.wait(m=>m.type==='state'&&m.state.teams[1].score===75)));
 p1.ws.close();await once(p1.ws,'close');const re=client(base.replace('http','ws'));clients.push(re);await once(re.ws,'open');re.send({type:'join',room:data.id,token:data.tokens.p1});const recovered=await re.wait(m=>m.type==='state');assert.equal(recovered.state.teams[1].score,75);assert.equal(recovered.state.buzzes.length,3);
 assert.equal((await fetch(base+'/multiplayer/game.js')).status,404);assert.equal((await fetch(base+'/questions.js')).status,404);assert.equal((await fetch(base+'/')).status,200);
 }finally{for(const c of clients)c.ws.terminate();wss.close();await new Promise(resolve=>server.close(resolve));}
});
test('Backup restores manual scores and masks without replaying old answers or credentials',()=>{const r=createRoom();act(r,'host',{type:'score',player:2,score:120});act(r,'host',{type:'round',round:'Vượt chướng ngại vật'});act(r,'host',question('text',{round:'Vượt chướng ngại vật',clue:1}));act(r,'host',{type:'tile',open:true});const backup=snapshot(r,'host');const fresh=createRoom();act(fresh,'host',{type:'restore',backup});assert.equal(fresh.teams[2].score,120);assert.deepEqual(fresh.opened,[1]);assert.equal(fresh.question,null);assert.notEqual(fresh.tokens.host,r.tokens.host);assert.throws(()=>act(fresh,'host',{type:'restore',backup:{...backup,teams:[]}}));});
