// Additional authored questions. Visual prompts are generated as local SVGs.
export const speedReasoning=[
['Lan có 24 viên kẹo, cho bạn một phần ba rồi ăn 2 viên. Lan còn mấy viên?','14 viên: 24 − 8 − 2.'],
['Dãy số 2, 6, 12, 20, 30 tăng lần lượt 4, 6, 8, 10. Số tiếp theo là gì?','42'],
['Một lớp có 18 nữ và 12 nam. Nữ chiếm bao nhiêu phần trăm cả lớp?','60%'],
['Một xe đi 45 km trong 45 phút. Vận tốc trung bình là bao nhiêu km/h?','60 km/h'],
['Ba số chẵn liên tiếp có tổng 42. Số lớn nhất là bao nhiêu?','16'],
['Mua 4 quyển vở giá 8.000 đồng/quyển, đưa 50.000 đồng. Được trả lại bao nhiêu?','18.000 đồng'],
['Lúc 3 giờ đúng, góc nhỏ giữa kim giờ và kim phút là bao nhiêu độ?','90°'],
['Một hình vuông tăng cạnh lên gấp 3 lần. Diện tích tăng lên gấp mấy lần?','9 lần'],
['Có 5 người, mỗi người bắt tay mỗi người khác đúng một lần. Có bao nhiêu cái bắt tay?','10'],
['Một sợi dây dài 2 m được cắt thành các đoạn 25 cm. Có bao nhiêu đoạn?','8 đoạn'],
['Tìm số còn thiếu: 1, 4, 9, 16, 25, … (các số chính phương liên tiếp).','36'],
['Tổng hai số là 50, hiệu là 14. Số nhỏ là bao nhiêu?','18'],
['Một người đi 3 km về phía đông rồi 4 km về phía bắc. Khoảng cách thẳng đến điểm xuất phát là bao nhiêu km?','5 km'],
['Một bể chứa 120 lít nước. Dùng hết 25%, rồi thêm 15 lít. Bể có bao nhiêu lít?','105 lít'],
['Nếu hôm nay là thứ Ba thì sau đúng 100 ngày là thứ mấy?','Thứ Năm (100 chia 7 dư 2).'],
['Một số nhân 4 rồi trừ 7 được 29. Số đó là gì?','9'],
['Bốn bạn có tuổi trung bình 12. Tổng tuổi của bốn bạn là bao nhiêu?','48 tuổi'],
['Có 10 con gồm gà và thỏ, tổng 28 chân. Có bao nhiêu con thỏ?','4 con thỏ'],
['Một cuốn sách có 100 trang, đánh số từ 1 đến 100. Cần bao nhiêu chữ số để đánh số trang?','192 chữ số: 9 + 90 × 2 + 3.'],
['Một đoàn tàu dài 150 m chạy 10 m/s. Tàu đi qua hoàn toàn một cột mốc trong bao nhiêu giây?','15 giây'],
['Một đồng xu được tung 3 lần. Có bao nhiêu chuỗi kết quả sấp/ngửa có thể xảy ra?','8'],
['Hộp có 4 bóng đỏ và 6 bóng xanh. Lấy ngẫu nhiên 1 bóng, xác suất lấy được bóng đỏ là bao nhiêu?','2/5 (40%).'],
['Một tam giác có hai góc bằng 35° và 65°. Góc còn lại bằng bao nhiêu?','80°'],
['Giá một món hàng 200.000 đồng, giảm 15%. Giá mới là bao nhiêu?','170.000 đồng'],
['Có 8 điểm trên một đường tròn. Chọn 2 điểm làm hai đầu một dây cung. Có bao nhiêu dây cung khác nhau?','28'],
['Một máy làm 6 sản phẩm mỗi phút. Ba máy giống nhau làm trong 5 phút được bao nhiêu sản phẩm?','90'],
['Một người leo 5 bậc thang mỗi lượt. Sau 7 lượt còn 9 bậc. Cầu thang có bao nhiêu bậc?','44'],
['Hai số có tích 72 và một số bằng 8. Tổng hai số bằng bao nhiêu?','17']
];
// Each row lists items already in the correct ascending order; UI shuffles the prompt.
export const speedOrders=[
['từ nhỏ đến lớn',['0,2','1/4','0,3','1/2']],
['từ nhỏ đến lớn',['−5','−2','0','3']],
['theo độ dài tăng dần',['8 cm','1 dm','0,5 m','1 m']],
['theo khối lượng tăng dần',['50 g','0,2 kg','500 g','1 kg']],
['theo thời lượng tăng dần',['30 giây','2 phút','1/4 giờ','1 giờ']],
['từ nhỏ đến lớn',['2²','2³','3²','2⁴']],
['từ nhỏ đến lớn',['10%','1/5','0,4','75%']],
['theo thời điểm trong ngày',['06:45','09:30','12:15','18:00']],
['theo dung tích tăng dần',['100 ml','0,25 lít','500 ml','1 lít']],
['theo số cạnh tăng dần',['Tam giác','Tứ giác','Ngũ giác','Lục giác']],
['theo đơn vị thời gian từ ngắn đến dài',['Giây','Phút','Giờ','Ngày']],
['theo thứ tự bảng chữ cái tiếng Anh',['A','D','K','Z']],
['từ nhỏ đến lớn',['1/8','1/4','1/2','1']],
['theo diện tích tăng dần',['1 cm²','1 dm²','1 m²','1 km²']]
];
export const finishPairs=[
['25% của 240 bằng bao nhiêu?','60'],
['Tác giả bài thơ Bạn đến chơi nhà là ai?','Nguyễn Khuyến'],
['Quốc gia nào có thủ đô là Tokyo?','Nhật Bản'],
['Chất khí nào chiếm phần lớn thể tích không khí khô gần mặt đất?','Nitơ'],
['Từ tiếng Anh “teacher” nghĩa là gì?','Giáo viên'],
['Tổng các số từ 1 đến 10 bằng bao nhiêu?','55'],
['Động vật có xương sống sống dưới nước, thở bằng mang và thường có vây thuộc lớp nào?','Lớp Cá'],
['Đơn vị đo điện trở trong hệ SI là gì?','Ôm (ohm, Ω)'],
['Một hình thoi có hai đường chéo 10 cm và 6 cm. Diện tích là bao nhiêu?','30 cm²'],
['Truyện cổ tích Tấm Cám thuộc loại văn học dân gian hay văn học viết?','Văn học dân gian'],
['Lục địa nào chứa sa mạc Sahara?','Châu Phi'],
['Số nhị phân 101 biểu diễn số thập phân nào?','5'],
['Quá trình chất lỏng chuyển thành chất rắn gọi là gì?','Đông đặc'],
['Trong tiếng Anh, dạng số nhiều của “child” là gì?','Children'],
['Một hình tròn có bán kính 5 cm. Đường kính là bao nhiêu?','10 cm'],
['Đơn vị cơ bản đo nhiệt độ trong hệ SI là gì?','Kelvin (K)'],
['Quốc gia nào có thủ đô là Paris?','Pháp'],
['Ước chung lớn nhất của 18 và 24 bằng bao nhiêu?','6'],
['Tác giả truyện ngắn Lão Hạc là ai?','Nam Cao'],
['Ký hiệu hóa học Na là nguyên tố nào?','Natri'],
['Trái Đất tự quay quanh trục là nguyên nhân trực tiếp của hiện tượng ngày đêm hay bốn mùa?','Ngày đêm'],
['Một hình bình hành có đáy 8 cm, chiều cao 5 cm. Diện tích là bao nhiêu?','40 cm²'],
['Trong tiếng Anh, “beautiful” có nghĩa là gì?','Đẹp / xinh đẹp'],
['Bộ phận nào của cây thường đảm nhiệm hút nước và muối khoáng từ đất?','Rễ'],
['Đơn vị đo công và năng lượng trong hệ SI là gì?','Jun (joule, J)'],
['Bội chung nhỏ nhất của 6 và 8 bằng bao nhiêu?','24'],
['Điền từ: “Gần mực thì đen, gần đèn thì …”.','Sáng'],
['Thủ đô của Thái Lan là thành phố nào?','Bangkok (Băng Cốc)'],
['Số đối của −12 là số nào?','12'],
['Động vật có vú hô hấp bằng phổi hay mang?','Phổi'],
['Trong tiếng Anh, “yesterday” nghĩa là gì?','Hôm qua'],
['Một góc nhọn có số đo nhỏ hơn hay lớn hơn 90 độ?','Nhỏ hơn 90 độ (và lớn hơn 0 độ).'],
['Ký hiệu hóa học Cu là nguyên tố nào?','Đồng'],
['Châu lục nào có diện tích lớn nhất?','Châu Á'],
['Căn bậc hai số học của 144 bằng bao nhiêu?','12'],
['Tác giả bài thơ Tiếng gà trưa là ai?','Xuân Quỳnh'],
['Lực hút giữa Trái Đất và vật được gọi là trọng lực hay lực đàn hồi?','Trọng lực'],
['Từ tiếng Anh nào chỉ màu xanh lá cây?','Green'],
['Một khối lập phương có cạnh 4 cm. Thể tích là bao nhiêu?','64 cm³'],
['Đơn vị đo cường độ dòng điện trong hệ SI là gì?','Ampe (ampere, A)'],
['Đường xích đạo chia Trái Đất thành hai bán cầu nào?','Bán cầu Bắc và bán cầu Nam'],
['Phân số 18/24 rút gọn tối giản thành phân số nào?','3/4'],
['Câu “Ai ơi bưng bát cơm đầy” thuộc thể thơ dân gian nào khi ghép với câu tám tiếng tiếp theo?','Lục bát'],
['Ký hiệu hóa học Ag là nguyên tố nào?','Bạc'],
['Quá trình hơi nước chuyển thành nước lỏng gọi là gì?','Ngưng tụ'],
['Trong tiếng Anh, trái nghĩa của “hot” là gì?','Cold'],
['Một xe đi 120 km với vận tốc 40 km/h không nghỉ. Mất bao nhiêu giờ?','3 giờ'],
['Hành tinh nào gần Mặt Trời nhất?','Sao Thủy'],
['Một hình hộp chữ nhật dài 5 cm, rộng 4 cm, cao 3 cm có thể tích bao nhiêu?','60 cm³'],
['Nhạc cụ nào có các phím đen trắng, thường gọi là dương cầm?','Piano'],
['Một số chia cho 5 được thương 7, dư 3. Số đó là bao nhiêu?','38']
];
